#!/bin/bash

#SBATCH --job-name=ambigSingle
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=10000
#SBATCH --hint=nomultithread
#SBATCH --partition=cpu
#SBATCH --account=eesc
#SBATCH --time=2-00:00:00 # Job time limit: days-hours:minutes:seconds
#SBATCH --mail-user=rmummah@usgs.gov
#SBATCH --mail-type=START,END,FAIL
#SBATCH -o outfiles/singlerun-%j.out
#SBATCH -e outfiles/singlerun-%j.err


# TO RENAME WITHOUT ARRAY
## dummy-%j.out  # %j = job ID
## dummy-%j.err
## --mail-type=END,FAIL,ARRAY_TASKS # Receive emails when tasks are complete/fail by array task


## Load modules (you can see options using 'module avail')
module load jags cray-R

## Set the name of the R script to run, and the directory in which to save outputs
script=/caldera/hovenweep/projects/usgs/ecosystems/eesc/rmummah/bayes-ambig-detect/run-single.R

mod=$1
iter=$2
flag=$3

# run your script:
## Pass the name of the script to run as a variable called $script
## Pass the name of the output diretory as a variable called $outdir
## $SLURM_TASK_ID is a variable automatically generated by the bash input in line 9.

srun --cpu-bind=none Rscript $script $mod $iter $flag

#End script
