#!/bin/bash
 
#SBATCH --job-name=ambigMODU
#SBATCH --array=1-6000:1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=10000
#SBATCH --hint=nomultithread
#SBATCH --partition=cpu
#SBATCH --account=eesc
#SBATCH --time=2-00:00:00 # Job time limit: days-hours:minutes:seconds
#SBATCH --mail-type=ALL
#SBATCH --mail-user=rmummah@usgs.gov
#SBATCH -o outfiles/modU-%A_%a.out
#SBATCH -e outfiles/modU-%A_%a.err


# TO RENAME WITHOUT ARRAY
## dummy-%j.out  # %j = job ID
## dummy-%j.err
## --mail-type=END,FAIL,ARRAY_TASKS # Receive emails when tasks are complete/fail by array task


## Load modules (you can see options using 'module avail')
module load jags cray-R

## Set the name of the R script to run, and the directory in which to save outputs
script=/caldera/hovenweep/projects/usgs/ecosystems/eesc/rmummah/bayes-ambig-detect/03-fit-models-HPC/run-cluster-modU.R


# run your script:
## Pass the name of the script to run as a variable called $script
## Pass the name of the output diretory as a variable called $outdir
## $SLURM_TASK_ID is a variable automatically generated by the bash input in line 9.

srun --cpu-bind=none Rscript $script $SLURM_ARRAY_TASK_ID

#End script
